import { query } from '../../database/db.js';

export const insertData = async () => {

	const churchMembers = `
		INSERT INTO Church_members (name) VALUES
			('Aguiar, Stael de Melo'),
			('Almeida, Franciely Martins de'),
			('Alves, Fernando'),
			('Amaral, Jaqueline Monteiro'),
			('Anacleto, Djanira Aparecida de'),
			('Anacleto, Vagner Basílio'),
			('Andrade, Angelita'),
			('Andrade De Lima, Estela'),
			('Antuarez Guayapero, Jesus Daniel'),
			('Antuarez Guayapero, Josmari Valentina'),
			('Antuarez Guayapero, Mariangel del Valle'),
			('Antuarez Guayapero, Marisol Josefina'),
			('Antuarez Palma, Jose Francisco'),
			('Armoa, Sofia'),
			('Astudillo Astudillo, Edgar Jose'),
			('Baez Ojeda, Kevin Josue'),
			('Barros, Elianius'),
			('Barros, Igor Duarte'),
			('Barros, Kris Corrêa Duarte'),
			('Barua, Alana'),
			('Barua, Denis Augusto Buss'),
			('Batista, Admir Nunes'),
			('Batista, Anselma Paiani de Oliveira'),
			('Batista, Melissa Oliveira'),
			('Batista, Rebeca Oliveira'),
			('Bengnini, Guilhermina'),
			('Benitez De Paula, Erick Vitorio'),
			('Brito Lebed, Isabela Geovanna'),
			('Brito Lebed, Isabela Geovanna'),
			('Bueno Rodrigues, Kauane Vitória'),
			('Bueno Rodrigues, Maiara'),
			('Bueno Rodrigues, Ramon'),
			('Carvalho, Gabriel Adalberto'),
			('Castilho, Heitor Henrique'),
			('Castro, Bruno Henrique Oviedo de'),
			('Centa, Elesia'),
			('Centenaro, Amanda Caroline'),
			('Costa, Cristiane'),
			('Cristaldo, Debora Natasha'),
			('Cristaldo, Lucia Helena'),
			('Da Rosa Royer, Angela Maria'),
			('Da Silva, Gelcina'),
			('de Aquino Anacleto, Vitor Eduardo'),
			('Debastiani, Jenifer Natali da Rosa'),
			('de Jesus Figuera Salas, Eliangel'),
			('De Oliveira, Pamela Rogiane'),
			('De Paula Pereira, Natasha'),
			('Derhum, Caio'),
			('Derhum, Chloe'),
			('Derhum, Cibelle Rosana Da Silva'),
			('Derhum, Dérek'),
			('Derhum, Sarah'),
			('De Sant'' Anna, Aryane Caroline'),
			('de Sousa, Ketlen Mombelli'),
			('Dias, David Rafael Colombo'),
			('dos Anjos, Edson Benitez de Paulo'),
			('Duarte, Romulo Josue'),
			('Eliezer, Sotillo'),
			('Espicoz, Marilei Salete'),
			('Ferrari, Astra Gilda Uhlman'),
			('Ferrari, Jandir'),
			('Ferrari, Jessica Karina'),
			('Ferreira, Anderson'),
			('Ferreira, Caique'),
			('Ferreira, Itamar Rodrigues Mendes'),
			('Ferreira, Izaque Mendes'),
			('Ferreira, Raphael Oswaldo'),
			('Ferreira, Walisom diovans'),
			('Fuente Garcia, Samuel David'),
			('Fuentes Ochoa, Candelario Ramon'),
			('Furquim, Dulcilene Dos Santos'),
			('Galeano, Fernanda De Jesus'),
			('Galeano, Juliany'),
			('Garcia Romero, Mirna Josefina'),
			('Genehr, Oscar'),
			('Gersina, Louriana dos Santos'),
			('Gomes, Daniela Gervazio De'),
			('Gomes, Graziele Geruazio de'),
			('Gomes, Luiz Augusto Silva'),
			('Gonzalez Soares Sadim, Helayne Naheli'),
			('Gonzalez Soares Sadim, Marcos Emanuel'),
			('Gottems, Arthur Henrique'),
			('Gottems, Bernardo Bezerra'),
			('Gottems, Cristiano Luiz'),
			('Gottems, Simone Lima Bezerra'),
			('Gottems, Thomas Bezerra'),
			('Grisele, Alcides'),
			('Guayapero Perez, Marisela Del Carmen'),
			('Gustavo Jones Souza, Vieira'),
			('Horbatey, Gislayne Angelica'),
			('Jones Souza Vieira, Caio'),
			('Junior, José Vlademir dos Santos'),
			('Jurado Salina, Gersson Eleicer'),
			('Koszenieski, Isabella Vieira'),
			('Koszenieski, Marcelo'),
			('Koszenieski, Simone Rodrigues Vieira'),
			('Koszenieski, Valentina Vieira'),
			('Kreis Armoa, Rodrigo'),
			('Kreis Urunaga, Giovani Andres'),
			('Lacerda, Isabel Carlos'),
			('Lacerda, Nicholas Marcok de'),
			('Lacerda, Thomas Marcok de'),
			('Lara, Eduarda Julia de'),
			('Lebed, Jonathan Gabriel Brito'),
			('Lebed, Perla Gabriely Paiva Brito'),
			('Liborio, Ademir Clovis'),
			('Liborio, Laura'),
			('Lima, Anabeli de Melo'),
			('Lima, Anderson de'),
			('Lima, Fatimo'),
			('Lima Dos Santos, Guilherme'),
			('Luz, Jonathan Alves Lebed da'),
			('Luz, Josiane Aparecida da'),
			('Machado, Gabriel de Sousa'),
			('Machado, Rafael de Souza'),
			('Maia, Ingrid Karolaine'),
			('Marcok, Luzia Elvira Bispo'),
			('Marques, Ione Alves'),
			('Marques, Jonathan Willian'),
			('Martinez, Isabelina'),
			('Meira, Cleverson Luiz de'),
			('Meira, Pamela Lunara de'),
			('Meireles, Maria Aparecida Dos Santos'),
			('Melo, Diego De'),
			('Melo, Helamã de'),
			('Melo, Moroni de'),
			('Mendes, Edson Rodriguez'),
			('Mendes, Glória Elisabete Rodriguez'),
			('Mendes, Teófila Rodriguez de'),
			('Menezes, Liria Feltz de'),
			('Menezes, Lirinéia Feltz de'),
			('Meza, Delia Noemi'),
			('Miranda Brizuela, Aaron Marcos Daniel'),
			('Montiel Gomez, Dideiky Irabuck'),
			('Morais, Adilson Trindade de'),
			('Morais, Larissa Mariotto de'),
			('Morais, Rosileide Mariotto de'),
			('Moralles, Nadir Barth'),
			('Moreira, Vergulino Alves'),
			('Moreira Junior, Rafael De Faria'),
			('Muller, Miriam'),
			('Nogueira, Aline Lino da Silva'),
			('Nunes, Rodrigues Ana Carolina'),
			('Nunez, Paulo Henrique da Silva'),
			('Nunez, Samuel Minuzzi'),
			('Oliveira, Elidiane Gonçalves de'),
			('Oliveira, Robson Silva'),
			('Oliveira, Vitor'),
			('Padilha, Jonas Alessandro Muller'),
			('Padilha Muller, Amanda Maiara'),
			('Padilha Muller, Cesar Augusto'),
			('Padilha Muller, João Paulo'),
			('Padilha Muller, Moises Alexandre'),
			('Parolin, Gabriel Felipe'),
			('Pegorini, Priscila Luiza'),
			('Penagio, Victoria Leiny Winkellmann'),
			('Pereira, Elijane Vieira'),
			('Pereira, Jonathan'),
			('Pozzer, Naiane Beatriz'),
			('Primo, Eloide Alves'),
			('Resende, Cloves Zick'),
			('Ribeiro, Flavio'),
			('Ribeiro, Jaciara Barbara da Silva'),
			('Ribeiro, William Jonathan Soares'),
			('Ribeiro, Williara Barbara'),
			('Rocha dos Santos, Bruna Deocleciana'),
			('Rodrigues, Amaurí'),
			('Rodrigues, Ana Carolina'),
			('Rodrigues, Maria Cristina de Oliveira'),
			('Rodrigues, Rosana Machado Gonçalves'),
			('Rodriguez, Viviane Alice Nunes'),
			('Rolon, Bartholo'),
			('Romero Rodrigues, Isabel'),
			('Rosa, Dienifer Eduarda da Silva'),
			('Rosa, Eduardo Rossi'),
			('Rosa, Marcelo Gabriel dos Santos'),
			('Royer, Luis Carlos'),
			('Sadim, Benjamin Liberato Gonzalez Soares'),
			('Salvador, Izabel Vieira'),
			('Santiago, Liosmar Vieira'),
			('Santos, Carlos Pereira Dos'),
			('Santos, Gustavo Amaral dos'),
			('Savio, Atanasio'),
			('Silva, Alessandro Padilha Da'),
			('Silva, Alessandro Rosa da'),
			('Silva, Alexandre José Alencar'),
			('Silva, Bruno Kaua Padilha Da'),
			('Silva, Cleiton Alves da'),
			('Silva, Danúbia Inara Padilha Da'),
			('Silva, Gabriel Braga Biano'),
			('Silva, Jaqueline Souza da'),
			('Silva, João Vitor Lang Barreto da'),
			('Silva, Kristen do Carmo Rosa'),
			('Silva, Livia Braga Biano'),
			('Silva, Luiz Fernando da'),
			('Silva, Maria Lucia da'),
			('Silva, Moises Padilha Da'),
			('Silva, Odaglas Jones Vieira da'),
			('Silva, Otavio Luiz Soler da'),
			('Silva, Reinalda Braga Biano'),
			('Silva, Rosangela da'),
			('Silva, Sandro Padilha Da'),
			('Silva, Solange Padilha da'),
			('Silva, Wlamir Cristiano'),
			('Silveira, Pamela Da Silva Sales'),
			('Soares, Jonathan Lopes'),
			('Soares, Thais Christina Venite'),
			('Soares Cavalheiro Sklauski, Idalvina'),
			('Soares Gonzalez, Iluminada'),
			('Soares Sadim, Marcos Emiliano'),
			('Sobrinho, Cesar Abich Lino'),
			('Sotillo, Eliseo José'),
			('Sotto, Luzia Estefana'),
			('Tavares, Samuel'),
			('Telles, Lucia'),
			('Telles, Zelindo'),
			('Torres, Anderson Dos Santos'),
			('Torres, Caroline Leite Da Silva'),
			('Torres, Laura'),
			('Torres, Leticia'),
			('Torres, Lorena'),
			('Vargas Umau, Vitoria Cristina'),
			('Velásquez, Ramón Antonio'),
			('Velásquez, Yannys Mercedes de'),
			('Vieira, Cristielly Jhoicy Monteiro'),
			('Vieira, Jessica Alves Gonçalves'),
			('Vieira, Noemi Barbosa'),
			('Vieira, Silvia'),
			('Vieira Koszenieski, Davi');
  `;

	query(churchMembers)
		.then((res) => {
			console.log('Church members successfully inserted!');
			process.exit(0);
		})
		.catch((err) => {
			console.log(err);
			process.exit(0);
		});
};

insertData();