version: '3.8'
services:
  db:
    image: postgres:16.1
    container_name: db_lds
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 9492:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
